controller_manager:
  ros__parameters:
    use_sim_time: true
    update_rate: 200

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    robotnik_base_control:
      type: diff_drive_controller/DiffDriveController

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true
    publish_rate: 100.0

robotnik_base_control:
  ros__parameters:
    left_wheel_names:
      - front_left_wheel_joint
      - rear_left_wheel_joint
    right_wheel_names:
      - front_right_wheel_joint
      - rear_right_wheel_joint
    wheel_separation: 0.419
    wheel_radius: 0.11
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0
    odom_frame_id: odom
    base_frame_id: base_footprint
    enable_odom_tf: true
    cmd_vel_timeout: 0.1
    publish_rate: 50.0
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.5
        has_acceleration_limits: true
        max_acceleration: 2.5
        has_jerk_limits: false
        max_jerk: 0.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 3.0
        has_acceleration_limits: true
        max_acceleration: 2.5
        has_jerk_limits: false
        max_jerk: 0.0